variables:
  IMAGE_NAME: $DOCKER_USER/python-flask-app
  IMAGE_TAG: ver-1.0

stages:
  - test
  - build
  - deploy

lets_test:
    stage: test
    image: python:3.10-alpine
    before_script:
    - uname -a
    script:
    - python --version

build_image:
    stage: build
    image: docker:24.0.2
    services:
      - docker:24.0.2-dind
    variables:
      DOCKER_TLS_CERTDIR: "/certs"
    before_script:
      - docker login -u $DOCKER_USER -p $DOCKER_USER_PASSWORD
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
#Test2
deploy_image:
    stage: deploy
    before_script:
      - chmod 400 $SSH_KEY
    script:
       - ssh -o StrictHostKeyChecking=no -p 2222 -i $SSH_KEY $DEPLOY_USER@$DEPLOY_SERVER "
        docker login -u $DOCKER_USER -p $DOCKER_USER_PASSWORD &&
        docker ps -aq | xargs docker stop | xargs docker rm &&
        docker run -d -p 8000:8000 $IMAGE_NAME:$IMAGE_TAG"
